create user DEMO identified by 123456;

select username from dba_users;

GRANT CREATE TABLE TO DEMO;

grant create session to DEMO;

SELECT username, account_status FROM dba_users
WHERE username = 'smithj'

CREATE SCHEMA FLIGHTS AUTHORIZATION demo;

CREATE TABLE CLIENT_ROLE
(RECORD_NO Number(5,0),
USER_NAME VARCHAR2(20),
USER_ROLE VARCHAR2(20),
STATUS VARCHAR2(1),
LAST_UPDATE_DATE TIMESTAMP (6),
PRIMARY KEY(RECORD_NO));

DROP TABLE ROLES;


CREATE TABLE ROLES
(RECORD_NO Number(5,0),
ROLE_ID VARCHAR2(20),
ROLE_VALE VARCHAR2(20),
STATUS VARCHAR2(1),
LAST_UPDATE_DATE TIMESTAMP (6),
PRIMARY KEY(RECORD_NO));


INSERT INTO ROLES (RECORD_NO, ROLE_ID, ROLE_VALE,STATUS,LAST_UPDATE_DATE) VALUES (1, 'ADMIN', 'ROLE_ADMIN','A',SYSDATE);
INSERT INTO ROLES (RECORD_NO, ROLE_ID, ROLE_VALE,STATUS,LAST_UPDATE_DATE) VALUES (2, 'USER', 'ROLE_USER','A',SYSDATE);

INSERT INTO CLIENT_ROLE (RECORD_NO, USER_NAME, USER_ROLE,STATUS,LAST_UPDATE_DATE) VALUES (1, 'hungnh', 'ROLE_USER','A',SYSDATE);

CREATE USER smithj
  IDENTIFIED BY pwd4smithj;

 GRANT CREATE TABLE TO DEMO;

SELECT * FROM Demo.CLIENT;

 CREATE TABLESPACE demo_spring
   DATAFILE 'demo_data.dbf'
   SIZE 100m;


  CREATE TABLESPACE tbs1
   DATAFILE 'tbs1_data.dbf'
   SIZE 10m;


 SELECT
   tablespace_name,
   file_name,
   bytes / 1024/ 1024  MB
FROM
   dba_data_files;


  ALTER USER DEMO quota 10M on tbs1;

 select ROLE_VALE FROM Client c INNER JOIN CLIENT_ROLE cr ON c.USER_NAME = cr.USER_NAME and cr.STATUS = 'A'
             INNER JOIN ROLES r ON r.ROLE_ID = cr.USER_ROLE AND r.STATUS = 'A' WHERE c.USER_NAME = 'hungnh' AND c.STATUS = 'A'